<?php

/**
 * Implements hook_theme().
 */
function openid_connect_eauth_theme($existing, $type, $theme, $path) {
  return [
    'form__openid_connect_login_form' => [
      'template' => 'form--openid-connect-login-form',
      'base hook' => 'form',
    ],
  ];
}

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */
function openid_connect_eauth_theme_suggestions_form_alter(array &$suggestions, array $variables) {
  if (isset($variables['element']['#id']) && $variables['element']['#id'] == 'openid-connect-login-form') {
        $suggestions[] = 'form__openid_connect_login_form';
    }
}
